[package]
name = "webapp"
version = "1.0.0"
authors = ["Eric Bruneton"]
license = "GPL-3.0-only.txt"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
emulator = { path = "../emulator" }
scripts = { path = "../scripts" }
